### ISSUE TITLE
strange results

### ISSUE THREAD

**Issue by pannous** [mbebenita/WasmExplorer#10]
something is odd in the wast output for
```
char* _hello_(){
  return "world";
}
int _hell_no_(){return 16;}
```
They have exactly the same signature:
```
  (func $func0 (result i32)
    i32.const 16
  )
  (func $func1 (result i32)
    i32.const 16
  )
```
 which may or may not be defined thus:
```
  (data (i32.const 16)
    "world\00"
  )
```
 which is the proper place to discuss this behavior?

**Comment by yurydelendik** [comment]
You are correct: one of the "16" is referring. Closing as answered.

> which is the proper place to discuss this behavior?

Discussion of what is generated by llvm/binaryen/sm is out of scope of this project.
