### ISSUE TITLE
WasmEditor - encoding issues - 77 in array becomes M (not 4D) in the wasm data instruction

### ISSUE THREAD

**Issue by DanielBeckstein** [mbebenita/WasmExplorer#15]
**WasmExplorer-link to reproduce**
https://goo.gl/RquYRk

Declaring an C-Array like this:

int arr_0[2] = { **77**,2 };

results in the following data instruction in webassembly:
(data (i32.const 12) "**M**\00\00\00\02\00\00\00")
Note: (ASCI 77/0x4D == M)

which should probably be :
(data (i32.const 12) "**\4D**\00\00\00\02\00\00\00")

77 is not the only number that causes this behaviour:
This behaviour is already starting with **32** which becomes
"\00\00\00\02\00\00\00"

It looks like these might be encoding issues in the editor, not in the wasm conversion.

Note: I am using **optimization level 0,** or else the const values get optimized away.

**Comment by yurydelendik** [comment]
> (data (i32.const 12) "M\00\00\00\02\00\00\00")
> (data (i32.const 12) "\4D\00\00\00\02\00\00\00")

Both notations have proper syntax based on https://webassembly.github.io/spec/text/values.html#strings . WasmExplorer using upstream tools to generate WAST output (e.g. SpiderMonkey or binaryen)

Closing as invalid.
