### ISSUE TITLE
Service down?

### ISSUE THREAD

**Issue by callahad** [mbebenita/WasmExplorer#2]
The POST to `service.php` isn't responding for me, and I don't seem to be able to compile anything :(

**Comment by mbebenita** [comment]
There are some DNS issues, should be back up shortly. I'll update this issue once it's back up.

Thanks

**Comment by mbebenita** [comment]
Okay, service is back up.

**Comment by callahad** [comment]
Thanks! WasmExplorer is invaluable when I'm speaking at meetups and conferences about WebAssembly. I really appreciate it. :)

**Comment by mbebenita** [comment]
Ah, that's great. I didn't realize people were using it yet. :)
