### ISSUE TITLE
Update compiler toolchain (but not today)

### ISSUE THREAD

**Issue by callahad** [mbebenita/WasmExplorer#3]
Hello!

Looks like Canary and Nightly are now looking for .wasm files with [binary version 0xC](https://github.com/WebAssembly/design/pull/811) while the compiler here still produces the previous 0xB version. Sounds like an update of emsdk is in order :)

But please don't update today this today, since @jasonbock is presenting at [VSLive](https://vslive.com/Events/Anaheim-2016/Sessions/Thursday/TH18-Assembling-the-Web-A-Tour-of-WebAssembly.aspx) in a few hours, and plans on using the WasmExplorer in his demos.

Also, @mbebenita:
1. Are you going to be at the All-Hands in December?
2. What's your drink of choice?
3. Are you checking a bag?

Thanks!

**Comment by mbebenita** [comment]
1. Yes, I'll be there.
3. Scotch Whisky.
2. No, but I'm sure we'll finish it before we leave.

**Comment by jayphelps** [comment]
Digged in to upgrade this to 0xD but it looks like all the magic is in `http://areweflashyet.com/tmp/wasm/service.php` which I can't find the source for 😄

**Comment by yurydelendik** [comment]
The toolchain was updated today.

**Comment by yurydelendik** [comment]
> which I can't find the source for

We want to run the source code by somebody who can validate the security of the solution first to avoid surprises.

**Comment by mbebenita** [comment]
So the issue here is that we're feeding LLVM code that we don't trust, and we don't know how to secure that property on the server side. So, right now we are very conservative and don't allow any includes.

**Comment by jayphelps** [comment]
@yurydelendik NICE. Thank you much. If it's easy, it would be great to have the ability for it to output the stack machine version of s-expressions rather than the AST macro-like form. Since wasm itself is a stack machine language, it helps when I'm teaching others to be able to more accurately represent, even if the AST form is easier to grok.

**Comment by mbebenita** [comment]
@callahad I drank the bottle of whisky you gave us, but since Yury actually updated it, I'll need to pass on the gift and get him a bottle of cognac.

**Comment by yurydelendik** [comment]
> it would be great to have the ability for it to output the stack machine version of s-expressions rather than the AST macro-like form.

@jayphelps yes, it is in the plans. Currently WebAssembly people working on making a well-defined form of it. I'll see what I can do on our end. Can you open a separate issue for that?
