### ISSUE TITLE
Add option to use BaseCompiler

### ISSUE THREAD

**Issue by dannas** [mbebenita/WasmExplorer#4]
I've just started working on a wasm SpiderMonkey issue  with no previous exposure to WebAssembly. This tool has been very helpful in reducing my learning curve.

It would be great if WasmExplorer had an option to display BaseCompiler output as well. Would simplify performance work such as https://bugzilla.mozilla.org/show_bug.cgi?id=1316801.

### Some useful links
Baseline compilation can be triggered via the SpiderMonkey js shell option --wasm-always-baseline.

Suggestions on how to generate the baseline assembly code can be found [in this issue comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1316803#c8) and on the wiki page [SpiderMonkey Hacking Tips](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Hacking_Tips#Printing_asm.jswasm_generated_assembly_code_(from_gdb))

Thanks for a great tool!

**Comment by yurydelendik** [comment]
@dannas as a workaround you can use API for jsshell [wasmExtractCode](https://bugzilla.mozilla.org/show_bug.cgi?id=1309583) to extract machine generated code -- you can use disassembler of your choice to dump the disassembly. You can export a function body compiled with BaseCompiler as well as from simulator ARM enabled shell.

**Comment by yurydelendik** [comment]
Fixed in version 2.7
