### ISSUE TITLE
Option to output stack machine form of wast, not AST

### ISSUE THREAD

**Issue by jayphelps** [mbebenita/WasmExplorer#5]
It would be great to have the ability for it to output the stack machine version of s-expressions rather than the AST macro-like form.

Since wasm itself is now a stack machine language, it helps when I'm teaching others to be able to more accurately represent, even if the AST form is easier to grok for some.

If support allows, it might be neat to have it default to stack with the option to AST, at least until some confident spec of the text format turns up.

Cc/ @yurydelendik

**Comment by yurydelendik** [comment]
Added "Clean WAST" option in v2.5 -- it is close to what we need, it is what Firefox produces in view source.

**Comment by jayphelps** [comment]
@yurydelendik shit I don't know how I missed that new option. Sorry! It's exactly what I was looking for. Feel free to close, unless there's additional things you want to do before an official format is specified

**Comment by yurydelendik** [comment]
> I don't know how I missed that new option

You did not. I just added it.

**Comment by jayphelps** [comment]
@yurydelendik oh. :man_facepalming: well now I feel less dumb. sneaky sneaky.

**Comment by cyberixae** [comment]
I did miss it even though it was there. I was expecting it to be the default so I wasn't looking for a configuration options. Also, I though to myself "this is the old format, it hasn't been updated yet".
