### ISSUE TITLE
Make wasm Module available in Browser

### ISSUE THREAD

**Issue by pannous** [mbebenita/WasmExplorer#8]
Feature request: Make the compiled wasm Module available directly in Browser debug window, without fetch('xyz.wasm')

**Comment by pannous** [comment]
and maybe in the GUI via _run_ button

**Comment by yurydelendik** [comment]
You will need JS glue code to run that. Also have other code (codemirror, capstone, etc) will interfere with debugging. Moving that into separate system (jsbin, jsfiddle, just a simple html page) might have a better choice.

**Comment by pannous** [comment]
I thought you already have the wasm binary array in the browser?
Even if not, getting it should be trivial?
Am I missing something?
Not talking about complicated debugging features, just having the result of your 'compilation' in your F12 console. wasm.hello("world")

**Comment by yurydelendik** [comment]
> Not talking about complicated debugging features, just having the result of your 'compilation' in your F12 console. aout.hello("world")

I'm sorry, I really don't  understand your use case. What's `aout.hello`? Can you be more specific and provide exact steps to reproduce the expected result?

How "Run" command will know which function to execute, which parameters and imports needs to be provided?

**Comment by mbebenita** [comment]
@yurydelendik I think @pannous means that it would be nice to have the generated module as a global in the browser's console, so a user could then click Compile and/or Assemble and then be able to write commands in the JS console to play around with the compiled module. @pannous am I understanding your use case correctly?

**Comment by pannous** [comment]
I just saw a great video about WasmExplorer, at some point the presenter wanted to _do_ something with his code, therefore he locally saved it, and did some manual fetch(...) command.
My suggestion is to get rid of this saving and fetching and just have the result of fetch() available automatically.

**Comment by pannous** [comment]
@mbebenita exactly ;)

**Comment by mbebenita** [comment]
@pannous you may want to try a related tool - https://wasdk.github.io/WasmFiddle/?5z6xr#

**Comment by pannous** [comment]
@mbebenita most wonderful, kind and fast, thanks
