### ISSUE TITLE
Source of service.php?

### ISSUE THREAD

**Issue by potch** [mbebenita/WasmExplorer#9]
Would be cool to let people run their own compile server or figure out what magic you're doing to replicate locally.

**Comment by yurydelendik** [comment]
(If you are looking to produce clean wast output, check https://gist.github.com/yurydelendik/4eeff8248aeb14ce763e)

**Comment by yurydelendik** [comment]
Here you go https://github.com/wasdk/wasmexplorer-service . Closing as resolved.
